### ISSUE TITLE
Problem 47 "Contain Yourself" is incompatible with newer Clojure versions

### ISSUE THREAD

**Issue by alexander-yakushev** [4clojure/4clojure#266]
This problem uses the following test:

``` clojure
(not (contains? '(1 2 4) __))
```

I don't know at which point exactly `contains?` was changed, but in Clojure 1.7-alpha3 it throws `IllegalArgumentException: contains? not supported on type: clojure.lang.PersistentList`.

I suggest the test is modified or removed (even if 4Clojure itself doesn't plan to update to newer version of Clojure yet).

**Comment by peter-lyons-kehl** [comment]
Hi Alexander,

Thank you for reporting. For ForeClojure-Android, too.

This has been fixed already. http://www.4clojure.com/problem/47 now shows `(not (contains? '[1 2 4] __))`. Would you close this ticket, please.

**Comment by alexander-yakushev** [comment]
Thank you!
