### ISSUE TITLE
"Times Solved" column on the problems page does not sort correctly.

### ISSUE THREAD

**Issue by mhavard999** [4clojure/4clojure#269]
When using the up and down arrow buttons next to the "Times Solved" column on http://www.4clojure.com/problems, the rows do not sort themselves according to number of times solved.

The problems are not sorted correctly for either ascending or descending order, as shown by the screenshots below:
![descendingsort](https://cloud.githubusercontent.com/assets/1484098/6695238/0a40aace-ccb6-11e4-8d03-8815ba78e876.png)
![ascendingsort](https://cloud.githubusercontent.com/assets/1484098/6695243/12e66ea2-ccb6-11e4-9e66-89e5ed3fb864.png)

You can get the desired behavior by just clicking on the "Solved?" column, but it makes sense for this behavior to work on the "Times Solved" column as well.

**Comment by nbeloglazov** [comment]
I believe the behaviour is correct. In your screenshot problems are sorted by "Submitted By" field. It might  confusing but sort arrows are aligned to the right while column name is aligned to the left. So sort arrows for "Times solved" column are on the right of the text. Also if you press on "Times solved" cell it sorts problems as expected.

**Comment by mhavard999** [comment]
Ah, my bad.  That was not very observant of me.
