### ISSUE TITLE
Restrictions on 121

### ISSUE THREAD

**Issue by devm33** [4clojure/4clojure#272]
Problem 121, the Universal Computation Engine problem, has no restrictions but given the nature of the problem it would have been helpful to know that `eval` and `resolve` etc are not allowed. Perhaps a note in the description with something to that effect.

**Comment by markw** [comment]
+1

**Comment by amcnamara** [comment]
done. closing.

**Comment by amalloy** [comment]
eval and resolve (and some other things that would let you circumvent the sandbox) are restricted form *every* problem, so I'm not sure it's correct to note them as special restrictions for 121.

**Comment by amcnamara** [comment]
agreed, but this problem (and perhaps a few others) really try to reproduce similar functionality. most problems don't lead people to investigate eval and such.

it seems like a really common theme, any thoughts on how to communicate this clearer? similarly macro-expansion gets some folks with the restricted list.

**Comment by amcnamara** [comment]
perhaps we should have two classes of restricted functions, "restrictions" and "special restrictions" where the first are default common to all problems and would show up an all problem views and the second specific to that problem's solution.  still not sure what to do about macro expansion though.

**Comment by devm33** [comment]
awesome thank you @amcnamara!

My two cents is that the more communication the better =)
