### ISSUE TITLE
Update Clojure to 1.7

### ISSUE THREAD

**Issue by darker0n** [4clojure/4clojure#275]
It's very important, because in last versions added new build-in functions

**Comment by amcnamara** [comment]
We get asked this a lot; we are limited in our ability to update clj by the sandbox environment the solutions run in (https://github.com/Raynes/clojail).

It's very unlikely that these projects will be updated to a more modern runtime, luckily the spirit of the site is to reimplement common functionality with the barest core so it should still be useful for people learning the language!

That being said, if you're interested in updating clojail you should drop @Raynes a message!
