### ISSUE TITLE
#56 does not accept a valid solution

### ISSUE THREAD

**Issue by VaclavSynacek** [4clojure/4clojure#285]
Problem 56 fails at first test with solution `#(keys (reduce (fn [a x] (assoc a x 1)) {} %))` even though `(= (#(keys (reduce (fn [a x] (assoc a x 1)) {} %)) [1 2 1 3 1 2 4]) [1 2 3 4])` returns true in clojure version 1.8.0.

**Comment by amalloy** [comment]
This is not a correct solution. Maps are unordered, so your `keys` could reorder the input sequence arbitrarily, but the requirement is that it stays in the correct order. That it happens to work with a particular version of clojure on a particular JVM does not make it correct.
